FROM node:14 as node
WORKDIR /app

COPY package.json /app
RUN npm install
COPY . /app
RUN npm run build --prod

FROM nginx:1.21.4-alpine-perl as nginx
COPY --from=node /app/dist/frontend /usr/share/nginx/html