version: '3'
services:
  prometheus:
    image: prom/prometheus:v2.20.1
    container_name: prometheus_practica
    networks:
      - external-network
    ports:
      - ${PROMETHEUS_PORT}
    depends_on:
      - backend-service
    links:
      - backend-service
    volumes:
      - ./backend/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:7.1.5
    container_name: grafana_practica
    networks:
    - external-network
    ports:
    - ${GRAFANA_PORT}
    volumes:
    - ./backend/grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    - myGrafanaVol:/var/lib/grafana
    environment:
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_INSTALL_PLUGINS: grafana-clock-panel 1.0.1
    depends_on:
    - prometheus

volumes:
  myGrafanaVol:

networks:
  external-network:
    external:
      name: external-network